# Generated by Django 3.0.1 on 2019-12-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetest',
            options={'verbose_name_plural': 'Imagetest'},
        ),
        migrations.AddField(
            model_name='imagetest',
            name='text',
            field=models.TextField(default='Automatic Slide', max_length=255),
        ),
    ]
