# Generated by Django 3.0.1 on 2019-12-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0002_auto_20191227_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagetext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Automatic Slide', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Imagetext',
            },
        ),
    ]
