# Generated by Django 3.0.1 on 2020-01-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiv', '0003_imagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetest',
            name='photo',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
